# Generated by Django 5.2 on 2025-04-11 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='polls_covers')),
                ('title', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('FD', 'Food'), ('TI', 'Technology'), ('PO', 'Politics'), ('SP', 'Sports'), ('ED', 'Education'), ('EN', 'Entertainment'), ('HE', 'Health'), ('TR', 'Travel'), ('EV', 'Environment'), ('SC', 'Science'), ('BU', 'Business'), ('OT', 'Other')], default='OT', max_length=3)),
                ('is_public', models.BooleanField(blank=True, default=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('max_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(blank=True, default=False, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('results_visible', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
