# Generated by Django 5.2 on 2025-04-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='was_edited',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
