# Generated by Django 5.2 on 2025-04-12 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='votes.poll'),
        ),
    ]
