# Generated by Django 5.2 on 2025-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0007_polloption'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='code',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
    ]
