# Generated by Django 5.2 on 2025-04-16 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0008_poll_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='stared_polls', to=settings.AUTH_USER_MODEL),
        ),
    ]
