# Generated by Django 5.2 on 2025-04-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0009_alter_poll_code_alter_poll_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
