# Generated by Django 5.2 on 2025-04-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0010_alter_poll_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, null=True),
        ),
    ]
