# Generated by Django 5.2 on 2025-04-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0011_alter_poll_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='voting_users_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
