# Generated by Django 5.2 on 2025-04-21 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0012_poll_voting_users_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='voting_users_count',
        ),
        migrations.AddField(
            model_name='poll',
            name='voting_users_count',
            field=models.ManyToManyField(blank=True, related_name='online_polls', to=settings.AUTH_USER_MODEL),
        ),
    ]
