# Generated by Django 5.2 on 2025-04-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0013_remove_poll_voting_users_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='voting_users_count',
            new_name='voting_users',
        ),
    ]
