# Generated by Django 5.2 on 2025-04-25 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0014_rename_voting_users_count_poll_voting_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='voting_users',
        ),
    ]
